function Robot = InitEV3(q0)


% Get this data from sensors
hsvL = [0 0 0];
hsvR = [0 0 0];
idxL = 1;
idxR = 1;
posL = [0 0]';
posR = [0 0]';
dist = 1;
fi = 0;

PF = struct('nParticles', 100,...
            'xP', zeros(3, 100));

Robot = struct('R', 0.05,...
               'L', 0.15,...
               'q', q0, ...
               'xP', [0 0 0]', ...
               'hsvL', hsvL,...
               'hsvR', hsvR,...
               'idxL', idxL,...
               'idxR', idxR,...
               'posL', posL,...
               'posR', posR,...
               'dist', dist,...
               'fi', fi,...
               'PF', PF); 

DriverRGB();
DriverGyro();
DriverDist();
ParticleFilterInit();

end



