function Robot = InitEV3()

global v w
global PolygonMapColors
global Walls WallsKeepOut
global ObstaclesCenters Obstacles ObstaclesKeepOut
global Nodes Path Goal
global PF 
global Motion
global SenRGB SenDist SenGyro

v = 0;
w = 0;

PolygonMapColors = [];
Walls = []; 
WallsKeepOut  = [];
Nodes = [];

load('PolygonMap/PolygonColorData.mat');
load('Enviroment/Walls.mat');
load('Enviroment/WallsKeepOut.mat');
load('PathPlanning/Nodes.mat');

ObstaclesCenters = zeros(4,2);
Obstacles = zeros(32,4);
ObstaclesKeepOut = zeros(32,4);

Path = zeros(1,100);
Goal = 0;

PF = InitParticleFilter();
Motion = InitMotion();

SenRGB = InitSenRGB();
SenDist = InitSenDist();
SenGyro = InitSenGyro();

% Get this data from sensors
hsvL = [0 0 0];
hsvR = [0 0 0];
idxL = 1;
idxR = 1;
posL = [0 0]';
posR = [0 0]';
dist = 1;
fi = 0;

Robot = struct('R', 0.05,...
               'L', 0.15,...
               'q', [0 0 0]', ...
               'xP', [0 0 0]', ...
               'hsvL', hsvL,...
               'hsvR', hsvR,...
               'idxL', idxL,...
               'idxR', idxR,...
               'posL', posL,...
               'posR', posR,...
               'dist', dist,...
               'fi', fi,...
               'q_path', [0 0 0]',...
               'v', v,...  
               'w', w,...
               'Walls',Walls,...
               'WallsKeepOut', WallsKeepOut,...
               'ObstaclesCenters', ObstaclesCenters,...
               'Obstacles', Obstacles,...
               'ObstaclesKeepOut', ObstaclesKeepOut,...
               'Nodes', Nodes,...
               'Path', Path,...
               'Goal', Goal,...
               'PF', PF,...
               'Motion', Motion,...
               'SenRGB', SenRGB,...
               'SenDist', SenDist,...
               'SenGyro', SenGyro); 
           
end



