function BF = InitBayesFilter()

Aprio = ones(96,1) * 1/96;
Apost = ones(96,1) * 1/96;


BF = struct('Aprio', Aprio,...
            'Apost', Apost,...
            'bestMtcVal', 0,...
            'bestMtcIdx', 0,...
            'Flag_NewMotion', false,...
            'Flag_TurnLeft', false,...
            'Flag_TurnRight', false,...
            'Flag_Forward', false);




end
