function PF = InitParticleFilter()

nParticles = 2*96;

PF = struct('State', 'Init',...
            'Estimate', 'Searching',...
            'nParticles', nParticles,...
            'xParticles', zeros(3, nParticles),...
            'x', 2500,...
            'y', 1800,...
            'fi', pi/2,...
            'Flag_Reinit', false);

end
        