NodeA =  struct('x', 1,...
                'y', 2,...
                'name', 'A',...
                'cost', 99999,...
                'path', 0,...
                'ConnIndex', [3,5,4,2,0],...
                'ConnWeight',[2,4,6,3,99]);

NodeB =  struct('x', 3,...
                'y', 2,...
                'name', 'B',...
                'cost', 99999,...
                'path', 0,...
                'ConnIndex', [1,4,6,0],...
                'ConnWeight',[3,5,5,99]);
            
NodeC =  struct('x', 0,...
                'y', 1,...
                'name', 'C',...
                'cost', 99999,...
                'path', 0,...
                'ConnIndex', [1,5,0],...
                'ConnWeight',[2,1,99]);
            
NodeD =  struct('x', 2,...
                'y', 1,...
                'name', 'D',...
                'cost', 99999,...
                'path', 0,...
                'ConnIndex', [1,5,6,2,0],...
                'ConnWeight',[6,2,1,5,99]);
            
NodeE =  struct('x', 1,...
                'y', 0,...
                'name', 'E',...
                'cost', 99999,...
                'path', 0,...
                'ConnIndex', [1,3,6,4,0],...
                'ConnWeight',[4,1,4,2,99]);
            
NodeF =  struct('x', 3,...
                'y', 0,...
                'name', 'F',...
                'cost', 99999,...
                'path', 0,...
                'ConnIndex', [2,4,5,0],...
                'ConnWeight',[5,1,4,99]);
Nodes = [NodeA NodeB NodeC NodeD NodeE NodeF]; 

save('Dijkstra_example_nodes', 'Nodes');