function MC = InitMotionControler()

ControlerState = 'LineTracking';

Motion = InitMotion();

MC = struct('ControlerState', ControlerState,...
            'v',0,...
            'w',0,...
            'v_old',0,...
            'w_old',0,...
            'LF', Motion);
end
